add_newline = false
format = """
$directory\
$aws\
$git_branch\
$git_state\
$git_status\
$battery\
$buf\
$c\
$docker_context\
$elixir\
$golang\
$java\
$dotnet\
$julia\
$lua\
$memory_usage\
$nodejs\
$package\
$ruby\
$rust\
$scala\
$zig\
$cmd_duration\
$memory_usage\
$hostname\
\n$character"""

[directory]
read_only = ' ó°Œ¾'
fish_style_pwd_dir_length = 1
truncation_length = 3
use_logical_path = true

[character]
success_symbol = '[â¯](purple)'
error_symbol = '[â¯](red)'
vimcmd_symbol = '[î˜«](green)'

[git_status]
format = '[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)'
style = 'cyan'
conflicted = 'ğŸ³'
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_state]
format = ' \([$state( $progress_current/$progress_total)]($style)\)'
style = 'bright-black'

[cmd_duration]
format = ' [$duration]($style) '
style = 'yellow'

[python]
format = ' [$virtualenv]($style) '
style = 'bright-black'
symbol = 'îˆµ '

[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = 'ïƒ‚ '
disabled = false

[azure]
format = ' [$symbol($subscription)]($style)'
symbol = 'ó° … '
disabled = false

[battery]
full_symbol = 'ó°¹ '
charging_symbol = 'ó°‚„ '
discharging_symbol = 'ó°‚ƒ '
unknown_symbol = 'ó°½ '
empty_symbol = 'ó°‚ '
format = ' [$symbol$percentage]($style) '
disabled = false

[[battery.display]]
threshold = 80
style = 'bold green'

[[battery.display]]
threshold = 50
style = 'bold yellow'

[[battery.display]]
threshold = 30
style = 'bold red'

[buf]
format = ' [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸ¦¬ '
detect_files = ['buf.yaml', 'buf.gen.yaml', 'buf.work.yaml']
style = 'bright-white'

[bun]
format = ' [$symbol($version )]($style) '
version_format = 'v${raw}'
symbol = 'ğŸ '
detect_files = ['bun.lockb', 'bunfig.toml']
disabled = false

[c]
symbol = 'î˜ '
format = '[$symbol($version(-$name) )]($style)'
version_format = 'v${raw}'
detect_extensions = ['c', 'h']
style = 'bold blue'

[conda]
symbol = 'ï„Œ '

[dart]
symbol = 'î˜ '

[docker_context]
symbol = 'ğŸ³ '
format = ' [$symbol$context]($style) '

[elixir]
symbol = 'î‰µ '

[elm]
symbol = 'î˜¬ '

[fossil_branch]
symbol = 'ï˜ '

[git_branch]
symbol = 'ï˜ '

[golang]
format = ' [$symbol($version )]($style)'
symbol = 'î˜§ '

[guix_shell]
symbol = 'ïŒ¥ '

[haskell]
symbol = 'î· '

[haxe]
symbol = 'î™¦ '

[hg_branch]
symbol = 'ï˜ '

[hostname]
style = 'bold green'
ssh_symbol = 'î¬ '

[java]
format = ' [${symbol}(${version} )]($style)'
symbol = 'î‰– '

[dotnet]
symbol = 'î¿ '
style = 'purple'
heuristic = true
format = ' [$symbol($version )($tfm )]($style)'

[julia]
symbol = 'î˜¤ '

[lua]
format = ' [$symbol($version )]($style)'
symbol = 'î˜  '

[memory_usage]
symbol = 'ó°› '
threshold = 75
format = ' $symbol [${ram}( | ${swap})]($style) '

[meson]
symbol = 'ó°”· '

[nim]
symbol = 'ó°†¥ '

[nix_shell]
symbol = 'ïŒ“ '

[nodejs]
format = ' [$symbol($version )]($style)'
symbol = 'îœ˜ '

[os]
format = ' [$symbol]($style)'
disabled = false

[os.symbols]
Alpaquita = 'îª¢ '
Alpine = 'ïŒ€ '
Amazon = 'ï‰° '
Android = 'ï…» '
Arch = 'ïŒƒ '
Artix = 'ïŒŸ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
DragonFly = 'îŠ '
Emscripten = 'ïˆ… '
EndeavourOS = 'ï†— '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ó°›“ '
Gentoo = 'ïŒ '
HardenedBSD = 'ó°Œ '
Illumos = 'ó°ˆ¸ '
Linux = 'ïŒš '
Mabox = 'î¬© '
Macos = 'ïŒ‚ '
Manjaro = 'ïŒ’ '
Mariner = 'ï‡ '
MidnightBSD = 'ï†† '
Mint = 'ïŒ '
NetBSD = 'ï€¤ '
NixOS = 'ïŒ“ '
OpenBSD = 'ó°ˆº '
openSUSE = 'ïŒ” '
OracleLinux = 'ó°Œ· '
Pop = 'ïŒª '
Raspbian = 'ïŒ• '
Redhat = 'ïŒ– '
RedHatEnterprise = 'ïŒ– '
Redox = 'ó°€˜ '
Solus = 'ó° ³ '
SUSE = 'ïŒ” '
Ubuntu = 'ïŒ› '
Unknown = 'ïˆ­ '
Windows = 'ó°² '

[package]
format = ' [$symbol$version]($style)'
symbol = 'ó°— '

[pijul_channel]
symbol = 'ï˜ '

[rlang]
symbol = 'ó°Ÿ” '

[ruby]
symbol = 'î‘ '

[rust]
symbol = 'î¨ '

[scala]
symbol = 'îœ· '

[zig]
format = ' [$symbol($version )]($style)'
